# Generated by Django 5.0 on 2024-03-07 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pedidos.cliente', verbose_name='Cliente'),
        ),
    ]
