# Generated by Django 5.0 on 2024-01-18 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_marca_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
