# Generated by Django 5.0 on 2024-01-18 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('productos', '0009_producto_activo_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Stock')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuracion.color', verbose_name='Color')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuracion.medida', verbose_name='Medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Presentación de producto',
                'verbose_name_plural': 'Presentaciones de productos',
                'db_table': 'presentacion',
            },
        ),
    ]
