# Generated by Django 5.0 on 2024-02-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de categoría'),
        ),
    ]
