# Generated by Django 5.0 on 2024-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('productos', '0013_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(through='productos.Presentacion', to='configuracion.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.ManyToManyField(through='productos.Presentacion', to='configuracion.medida'),
        ),
    ]
