# Generated by Django 5.0 on 2024-01-23 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_proveedor_contacto_celular_proveedor_contacto_email_and_more'),
        ('productos', '0011_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='presentacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='productos.presentacion', verbose_name='Presentacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='representante',
            field=models.CharField(max_length=150, verbose_name='Representante legal'),
        ),
    ]
