# Generated by Django 5.0 on 2024-02-10 02:10

import compras.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_detallecompra_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=9, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=11, validators=[compras.validators.validar_ruc], verbose_name='RUC'),
        ),
    ]
